#!/bin/bash

# Defining required variables

API_URL="https://pokeapi.co/api/v2/pokemon/"
DATA_FILE="data.json"
ERORR_FILE="error.txt"

# Making API request

curl -s $API_URL -o $DATA_FILE

# checking if the request was successful
if [ $? -ne 0 ]; then
  echo "$(date): failed to fetch data from API" >> $ERORR_FILE

else
  echo "Data successfully retrieved and saved to $DATA_FILE"

fi
